GRANT select, update, insert ON proyecto.usuario TO baranchr;
GRANT select, update, insert ON proyecto.ticket TO baranchr;
GRANT select, update, insert ON proyecto.proyecto TO baranchr;
GRANT select, update, insert ON proyecto.usuario TO bialimay;
GRANT select, update, insert ON proyecto.ticket TO bialimay;
GRANT select, update, insert ON proyecto.proyecto TO bialimay;
GRANT select, update, insert ON proyecto.usuario TO cuocokal WITH GRANT OPTION ;
GRANT select, update, insert ON proyecto.proyecto TO cuocokal WITH GRANT OPTION ;
GRANT select, update, insert ON proyecto.ticket TO cuocokal WITH GRANT OPTION ;
GRANT select, update, insert ON proyecto.proyecto TO galecjoh;
GRANT select, update, insert ON proyecto.usuario TO galecjoh;
GRANT select, update, insert ON proyecto.ticket TO galecjoh;
GRANT select, update, insert ON proyecto.usuario TO helbesim;
GRANT select, update, insert ON proyecto.ticket TO helbesim;
GRANT select, update, insert ON proyecto.proyecto TO helbesim;
GRANT select, update, insert ON proyecto.usuario TO lindhrik;
GRANT select, update, insert ON proyecto.proyecto TO lindhrik;
GRANT select, update, insert ON proyecto.ticket TO lindhrik;
GRANT select, update, insert ON proyecto.usuario TO mannaar WITH GRANT OPTION ;
GRANT select, update, insert ON proyecto.proyecto TO mannaar WITH GRANT OPTION ;
GRANT select, update, insert ON proyecto.ticket TO mannaar WITH GRANT OPTION ;
GRANT select, update, insert ON proyecto.usuario TO metcalau;
GRANT select, update, insert ON proyecto.proyecto TO metcalau;
GRANT select, update, insert ON proyecto.ticket TO metcalau;
GRANT select, update, insert ON proyecto.usuario TO nayyakun;
GRANT select, update, insert ON proyecto.ticket TO nayyakun;
GRANT select, update, insert ON proyecto.proyecto TO nayyakun;
GRANT select, update, insert ON proyecto.usuario TO parsojim;
GRANT select, update, insert ON proyecto.ticket TO parsojim;
GRANT select, update, insert ON proyecto.proyecto TO parsojim;
GRANT select, update, insert ON proyecto.proyecto TO rauchmel;
GRANT select, update, insert ON proyecto.ticket TO rauchmel;
GRANT select, update, insert ON proyecto.usuario TO rauchmel;
GRANT select, update, insert ON proyecto.usuario TO sussmkev WITH GRANT OPTION ;
GRANT select, update, insert ON proyecto.ticket TO sussmkev WITH GRANT OPTION ;
GRANT select, update, insert ON proyecto.proyecto TO sussmkev WITH GRANT OPTION ;